spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          kakao:
            client-id: 6479cf393f012936a0da49f7dd2f88eb
            authorization-grant-type: authorization_code
            client-name: DEVDEVDEV-TEST
            client-secret: yk58g3giuS6yqfNbit5yqWVZwDCV032t
            redirect-uri: http://localhost:8080/devdevdev/api/v1/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              # - openid
              - profile_nickname
              - account_email
              - name