jwt:
  header: Authorization
  secret: devdevdevtestdevdevdevtestdevdevdevtestdevdevdevtest
  redirectUri: http://localhost:8080/devdevdev/api/v1/members
  expiration:
    access: 100
    refresh: 1000000